blog_index:
    pattern:  /
    defaults: { _controller: MyBlogBundle:Default:index }

blog_new:
    pattern:  /new
    defaults: { _controller: MyBlogBundle:Default:new }

blog_show:
    pattern:  /{id}/show
    defaults: { _controller: MyBlogBundle:Default:show }
    requirements:
        id:  \d+

blog_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyBlogBundle:Default:delete }
    requirements:
        id:  \d+

blog_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyBlogBundle:Default:edit }
    requirements:
        id:  \d+
