blog_index:
    pattern:  /
    defaults: { _controller: MyBlogBundle:Default:index }

blog_new:
    pattern:  /new
    defaults: { _controller: MyBlogBundle:Default:new }

blog_show:
    pattern:  /{id}/show
    defaults: { _controller: MyBlogBundle:Default:show }
