blog_index:
    pattern:  /
    defaults: { _controller: MyBlogBundle:Default:index }

blog_new:
    pattern:  /new
    defaults: { _controller: MyBlogBundle:Default:new }
    requirements:
        _method: GET

blog_new_post:
    pattern:  /new
    defaults: { _controller: MyBlogBundle:Default:newPost }
    requirements:
        _method: POST

blog_show:
    pattern:  /{id}/show
    defaults: { _controller: MyBlogBundle:Default:show }
    requirements:
        id:  \d+

blog_delete:
    pattern:  /{id}/delete
    defaults: { _controller: MyBlogBundle:Default:delete }
    requirements:
        id:  \d+

blog_edit:
    pattern:  /{id}/edit
    defaults: { _controller: MyBlogBundle:Default:edit }
    requirements:
        id:  \d+
        _method: GET

blog_edit_post:
    pattern:  /{id}/edit
    defaults: { _controller: MyBlogBundle:Default:editPost }
    requirements:
        id:  \d+
        _method: POST
